### ISSUE TITLE
Use the picture realname.

### ISSUE THREAD

**Issue by karim789** [lwoggardner/shotwellfs#2]
The name of the picture is the id number of the picture in the shotwell database.
The real name would make it easier to find a picture on the real file system, or in shotwell.

**Comment by lwoggardner** [comment]
If your images all have unique (within event) titles then you can already use
    -o photo_path="%{title}"    

The default for "photo_path" is the shotwell ID because this is guaranteed to be unique within events.

Allowing %{filename} to be used in this option, referring to the source image's filename would be relatively straightforward to implement but it could not be the default because it is not guaranteed to be unique within events without some knowledge of the user.

**Comment by karim789** [comment]
Well you could verify duplicates and increment the name with a number, like Firefox does when saving a file with a name that already exists.

I hope I can help a bit when I understand ruby better.
